# application-local.yml

server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    name: frontend-server
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  cloud:
    config:
      enabled: false

# 로컬 게이트웨이 주소 (IntelliJ에서 실행 중인 게이트웨이)
gateway:
  uri: http://localhost:8000

# Book API 기본 URL (로컬 게이트웨이 경유)
#book:
#  api:
#    base-url: ${gateway.uri}/api/books

book:
  api:
    base-url: "http://localhost:9002"

jwt:
  expiration_time: 1800000
  refresh_expiration_time: 3600000